### ISSUE TITLE
dr-auto-sync config doesn't work

### ISSUE THREAD

**Issue by ChenPeng2013** [tikv/pd#6012]
### What did you do?

tiup deploy a cluster
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tiup/deploy"
  data_dir: "/tiup/data"
  arch: "amd64"
monitored:
  node_exporter_port: 19100
  blackbox_exporter_port: 19115
server_configs:
  tidb:
    log.level: "info"
  pd:
    pd-server.min-resolved-ts-persistence-interval: "1s"
    replication.location-labels:
    - dc
    - zone
    - host
    replication.max-replicas: 3
    replication-mode.replication-mode: "dr-auto-sync"
    replication-mode.dr-auto-sync.label-key: "dc"
    replication-mode.dr-auto-sync.primary: "dc1"
    replication-mode.dr-auto-sync.dr: "dc2"
    replication-mode.dr-auto-sync.primary-replicas: 2
    replication-mode.dr-auto-sync.dr-replicas: 1
    replication-mode.dr-auto-sync.tikv-sync-timeout-hint: "1m"
...
```
### What did you expect to see?
```
sh-4.2# curl http://10.233.76.25:2379/pd/api/v1/replication_mode/status
{
  "mode": "dr-auto-sync",
...
}
```
### What did you see instead?
```
sh-4.2# curl http://10.233.76.25:2379/pd/api/v1/replication_mode/status
{
  "mode": "majority",
...
}
```
### What version of PD are you using (`pd-server -V`)?
```
sh-4.2# ./pd-server -V
Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: 951dbc6873b058d72474fc4d5527165ec7366c98
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time:  2023-02-15 02:25:46
```
