### ISSUE TITLE
golang-ci revive.exported doesn't work

### ISSUE THREAD

**Issue by okJiang** [tikv/pd#8458]
# situation

we have been enabled `revive.exported`

https://github.com/tikv/pd/blob/9af28fc1d426697f90bba2f46b3957ec4f03bdcb/.golangci.yml#L119-L125

but it doesn't work, such as https://github.com/tikv/pd/blob/9af28fc1d426697f90bba2f46b3957ec4f03bdcb/pkg/core/region_tree.go#L446-L452

# How to fix it

add 
```yaml
issues:
  include:
    - EXC0012
    - EXC0014
```

ref https://github.com/u-root/uio/pull/14#issue-1592506863
